//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DSRPG.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Records
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public int Kills { get; set; }
        public int Deaths { get; set; }
        public int SoulsRecieved { get; set; }
        public int SoulsSpent { get; set; }
        public int Progress { get; set; }
        public int DamageGiven { get; set; }
        public int DamageTaken { get; set; }
        public int BossKills { get; set; }
    }
}
